development:
  adapter: postgresql
  encoding: unicode
  database: timeline_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: timeline_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: timeline_production
  pool: 5
  username: postgres
  password: 
