development:
  adapter: postgresql
  encoding: unicode
  database: timeline_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: timeline_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: ENV['DB_NAME']
  pool: 5
  username: ENV['DB_USER']
  password: ENV['DB_PASSWORD']
  host: ENV['HOST']
